### ISSUE TITLE
OTP 21: public_key.pem_entry_decode

### ISSUE THREAD

**Issue by hauptbenutzer** [shakrmedia/gcs-signer-elixir#3]
First off, thanks for putting this together!

The signing worked flawlessly until we upgraded to Elixir 1.6.6 and OTP 21. It seems the issue [you linked to](https://github.com/potatosalad/erlang-jose/issues/13#issuecomment-160718744) has been resolved in OTP 21 and `public_key.pem_entry_decode` now returns a sane response for gcloud private keys. Unfortunately, that means the special handling no longer works as expected and we get an argument error, since [`elem(3)`](https://github.com/shakrmedia/gcs-signer-elixir/blob/master/lib/gcs_signer.ex#L80) now returns an integer, instead of the private key binary.

I attempted to do a pattern match in order to keep backwards compatibility [like this](https://github.com/hauptbenutzer/gcs-signer-elixir/commit/9e7eaad06af1a83c494588ce1d340165f950f3f4#diff-0ace863873912b6324af45646ac213a0R88), which seems to work fine, at least for my keys.

What are your thoughts on this? I would clean this up a bit and open a PR.

**Comment by premist** [comment]
Hi @hauptbenutzer! First of all, thank you for looking into this and opening an issue. 

Your fix looks good to me, but I wonder that if there is a way to keep compatibility with OTP <=20. I don't mind bumping up OTP version for my own project but it might be a bit bothersome if someone else was depending on this library and it no longer works because of incompatibility with older OTP version.

Looking forward for your thoughts!

**Comment by hauptbenutzer** [comment]
The pattern match should have worked for OTP <= 20, but I took the chance to make it more explicit by actually [checking the OTP version](https://github.com/hauptbenutzer/gcs-signer-elixir/commit/e650c68776b524c2be56b9fa05e3a3182d76c182). Due to the use of the module attribute, the `if` should be inlined by the compiler.

**Comment by premist** [comment]
Resolved by #4.
